### ISSUE TITLE
[le boss final de la ZEP-12] tout casser !

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#87]
Ceci devrait normalement être la dernière _issue_ de la ZEP-12 à devoir être effectuée (sans compter les _bugfixs_, bien entendu). Il s'agit, tout simplement, de prendre la place des anciens modules articles et tutos, autrement dit tout casser. On doit donc ...
- [x] Placer le lien de rédaction dans le menu de l'utilisateur
- [x] Changer la _dropdown_: remplacer les catégories de tutos et mettre les bons liens (#87)
- [x] Prendre la place des urls `/articles/` et `/tutoriels/` (#30)
- [x] Vérifiez que le script de migration prend bien en compte les changements (#145)
- [x] Remplacer les liens de validation dans le menu des admins
- [x] intégration dans les profils (#74)
- [x] Autres ?

_brace yourself, painfull rebases are coming_ !

**Comment by artragis** [comment]
> Prendre la place des urls /articles/ et /tutoriels/

/!\/!\/!\ Il faudra modifier le script de migration qui pour l'instant gère très mal la mise en place des redirections puisqu'il joue sur le get_absolute_xxx_url qui se sert de `reverse` qui pointe vers les `/tutoriels/` et `/articles/` changer les prefix des vues aura un impact sur ces méthodes.

**Comment by pierre-24** [comment]
De manière générale, va falloir refaire un tour par là pour intégrer nos derniers changements respectifs (publications, commentaires)

**Comment by artragis** [comment]
j'ai changé le menu. Il n'y aura plus qu'à passer sur urls/**iniy**.py pour changer les tutoriels2 en tutoriels etc. (et changer les tutoriels en old_tutoriels)

**Comment by artragis** [comment]
j'ai envie de dire "\o/"

**Comment by pierre-24** [comment]
En effet :o 

Cela voudrait-il dire qu'on touche à la fin ?

**Comment by artragis** [comment]
Oui, on laisse juste le temps à @Hugo de terminer la recherche \o/

Et puis les .tuto
Et puis faudra qu'on regarde aux perfs car là c'est la cata sur la liste 
des articles et des tutos.

**Comment by pierre-24** [comment]
Et il manque aussi encore l'un ou l'autre TU, _according to_ #100

**Comment by artragis** [comment]
les TU n'impliquant pas de développement fonctionnel, ça s'ajoute même une fois la PR envoyée..

**Comment by pierre-24** [comment]
... Et deux de moins, non ?

... Ce qui signifie qu'on peut penser à mettre le champagne au frais ;)

**Comment by artragis** [comment]
en fait celle là je la fermerait quand nos urls s'appelleront /tutoriels/blabla et /articles/blabla et donc qu'on fera la PR

**Comment by pierre-24** [comment]
N'oublie pas que la PR finale devra contenir des trucs dans le `update.md` :)

**Comment by artragis** [comment]
elle en contient déjà :p

2015-08-05 16:13 GMT+02:00 Pierre Beaujean notifications@github.com:
