### ISSUE TITLE
intégrer la zep 12 au back de la zep 04

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#99]
Intégrer la ZEP-04:

Réparer et intégrer `content_item_part.html` et  `content_online_item_part.html` dans
- [x] La liste des contenus hors-lignes (#135)
- [x] La liste des contenus publiés (#135)
- [x] La page d'aide (pas de fix proposé, simplement de garder l'ancien _design_, voir https://github.com/zestedesavoir/zds-site/issues/2667)
- [x] La page d'accueil (sans tout casser !) **si tu cherches à corriger ce point, soit bien sur de ce que tu fait !**

**Comment by pierre-24** [comment]
_rien_

**Comment by GerardPaligot** [comment]
C'est pas déjà fait ça ?

**Comment by pierre-24** [comment]
Oui et non. Il se trouve que les gens de la ZEP-04 et nous sommes arrivés à la même conclusion (à savoir qu'un seul fichier nommé `content_item_part.html` ou un truc de ce gout là). Ce qui n'est pas fait, c'est de remettre les bonnes classes CSS au bon endroit pour que ça revienne au même (sans recasser la ZEP-04). Par exemple, sur la page d'accueil, tu peux voir que la liste est toujours celle des "tuto V1" :)

**Comment by Eskimon** [comment]
Je peux essayer de le faire ?

**Comment by artragis** [comment]
Oui !!!

2015-05-19 9:03 GMT+02:00 Eskimon notifications@github.com:

**Comment by GerardPaligot** [comment]
`content_item_part.html` est déjà dispo ?

**Comment by Eskimon** [comment]
le fichier oui, mais son contenu est "standard" :D Je regarde comment integrer les nouveautes justement

**Comment by Eskimon** [comment]
Ma premiere PR pour la ZEP-12 #emotions !

**Comment by pierre-24** [comment]
Bon, normalement, les listes de contenus et contenus publiés, c'est fait avec #135. 

Pour ce qui est de la bêta, de manière assez logique, les gens du _front_ on préféré garder ce qui se faisait déjà, donc on ne touche pas à ça non plus (je suis pas assez doué en front pour faire quoique ce soit sur ce point): voir https://github.com/zestedesavoir/zds-site/issues/2667 !

Pour ce qui est de la page d'accueil, _touche pas à ça petit con_. Tant que la ZEP-04 est en bêta(fix), je propose qu'on laisse faire pour éviter les rebases foireux.

**Comment by artragis** [comment]
@Eskimon a cassé le template des vues publiées.

**Comment by pierre-24** [comment]
Je sais bien, je viens de le fixer ;)

**Comment by artragis** [comment]
je merge de suite, tant pis pour travis, comme ça la QA peut commencer sur mon site.

**Comment by artragis** [comment]
> La page d'accueil (sans tout casser !) si tu cherches à corriger ce point, soit bien sur de ce que tu fait !

ça veut dire quoi?

**Comment by pierre-24** [comment]
"touches pas à ça piti con tant que la ZEP-04 est pas officiellement passée en prod' " :p

**Comment by artragis** [comment]
Oups, I did it again. (btw ça marche sur mon site)

**Comment by pierre-24** [comment]
If u say so ;)

(c'est pour toi que je dis ça, c'est toi qui est en charge des rebases :p )

**Comment by pierre-24** [comment]
... Et en fait, ça renvois vers les versions _offlines_, comme ça. Faut passer `public_tutorial` et `public_article` (qui sont les `PublishedContent`, pas les `PublishableContent`) à la template, dans ce cas là.

**Comment by artragis** [comment]
Je verrais plus tard si ça peut marcher.

**Comment by artragis** [comment]
et ça a fini par marcher

**Comment by pierre-24** [comment]
En effet ^^

**Comment by pierre-24** [comment]
... Mais `./zds/pages/utils.py:21:17: W292 no newline at end of file` ! :)

**Comment by artragis** [comment]
c'est pour vérifier que tu es attentif (par contre le fix, pas avant que je
sois rentré chez moi)

2015-05-20 16:59 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by Vayel** [comment]
Quelle QA ici ?

**Comment by artragis** [comment]
juste vérifier que le design de la ZEP 04 est partout le bon et que les
liens mènent aux bons endroits.

2015-05-21 11:47 GMT+02:00 Vincent notifications@github.com:

**Comment by Vayel** [comment]
La ZEP-04 ne concerne que la PA ?

**Comment by artragis** [comment]
PA et pages des listes.

**Comment by Vayel** [comment]
Les liens de la PA fonctionnent. Par contre, il y a un problème avec la recherche : http://zds.francoisdambrine.me/rechercher/?q=php

Pour les pages des listes, j'imagine qu'il s'agit de celles des tutoriels et des articles. A priori, pas de souci de ce côté-là.

**Comment by artragis** [comment]
la recherche, c'est normal, tout est foireux dans notre lien entre le 
module et la recherche.

**Comment by pierre-24** [comment]
La recherche, c'est "normal" (et un gros problème, par ailleurs).

Bon, par contre, fermez pas le ticket, on en à pas encore fini vu ce qui se prépare en prod' (genre du cache :p )

**Comment by artragis** [comment]
Le cache disparaissant, je passe en needqa

**Comment by pierre-24** [comment]
Ouaip', mais tes propres modif's _upstream_ vont probablement nous ennuyer ;)

(et tant mieux, d'ailleurs!)

**Comment by artragis** [comment]
non, c'est un copier/coller à la con que j'ai fait. donc il va le merger
gentiement.

2015-05-28 13:12 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by artragis** [comment]
Pourriez-vous jouer avec la page d'accueil pour voir si j'ai pas fait de connerie dans mon merge. Une fois cela fait, on pourra valider !

**Comment by pierre-24** [comment]
Le problème de la page d'acceil, c'est qu'elle est encore légèrement différente en _release_, donc on ne pourra être sur que quand la _release_ aura été publiée.

**Comment by artragis** [comment]
peut-on dire que c'est ok maintenant?

**Comment by pierre-24** [comment]
Oui ;)
